repos:
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.6
    hooks:
      - id: forbid-tabs
      - id: remove-tabs
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: trailing-whitespace
  - repo: https://github.com/AleksaC/hadolint-py
    rev: v2.14.0
    hooks:
      - id: hadolint
        args:
          - --failure-threshold=warning
          - --ignore=DL3008
          - --ignore=DL3007
  - repo: https://github.com/crate-ci/typos
    rev: v1.46.0
    hooks:
      - id: typos
        args:
          - --force-exclude
          - --hidden
          - --locale=en-gb
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.48.0
    hooks:
      - id: markdownlint-fix
        args:
          - --dot
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck
        args:
          - --severity=warning
          - --external-sources
          - --shell=bash
          - --exclude=SC2207
